/*
389. Find the Difference
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.
Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:
Input: s = "", t = "y"
Output: "y"
Constraints:
0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
*/
// Most Optimized Method
// Time Complexity O(n)
// Space Complexity O(n)
class Solution {
public:
    char findTheDifference(string s, string t) {
        unordered_map<char,int> f;
        for(char &ch:s){
            f[ch]--;
        }
        for(char &ch:t){
            f[ch]++;
        }
        char ans;
        for(auto i:f){
            if(i.second==1){
                ans =i.first;
                break;
            }
        }
        return ans ;
    }
};

class Solution {
public:
    char findTheDifference(string s, string t) {
        vector<int> f(26,0);
        for(char &ch:t){
            f[ch - 'a']++;
        }
        for( char &ch:s){
            f[ch - 'a']--;
        }
        char ans ;
        for(int i=0;i<26;i++){
            if(f[i]==1){
                ans = ('a'+i);
            }
        }
        return ans;
    }
};